test: signin
KubaBaniak/RecipeAppAuth pull request #6
Opened 2023-10-12 10:00 UTC by KubaBaniak

## TESTS FOR [THIS PR](https://github.com/KubaBaniak/RecipeAppAuth/pull/4)

2023-10-16 08:33 UTC, rad20c commented on src/auth/auth.service.ts
> +    if (!userPassword) {
https://github.com/KubaBaniak/RecipeAppAuth/pull/6/files#r1360312226

2023-10-16 08:36 UTC, rad20c commented on test/auth.e2e-spec.ts
> +    it(`should throw 401 - wrong password`, async () => {
I'd also add a test when user does not exist

2023-10-16 08:37 UTC, rad20c requested changes
check comments - at least `userCredentials` mock should be changed

2023-10-17 06:41 UTC, KubaBaniak commented on src/auth/__mocks__/user-credentials.repository.mock.ts
> +  }
My bad. I've made naming mistake. Both functions return same thing: `Promise<string | null>` which is password or null but name says `getUserCredentials...`

2023-10-17 07:22 UTC, rad20c approved these changes

2023-10-17 07:25 UTC, merged